### ISSUE TITLE
Add link to Heroku in readme

### ISSUE THREAD

**Issue by logart** [pavelwebdeveloper/food-storage-app#1]
Please modify readmi file so it will contain a link to the app hosted on heroku. This way it will be easier to check what is working right now.

**Comment by pavelwebdeveloper** [comment]
Added a link to the app hosted on heroku in the readmi file

**Comment by pavelwebdeveloper** [comment]
I am going to improve the look of front-end so I created a new branch for this. I called it "improve-the-look-of-front-end"
